import type { SpecDef } from "../model";

export const SPECS: readonly SpecDef[] = [
  {
    id: "battlecraft",
    classId: "warrior",
    name: "Battlecraft",
    icon: "sword",
    nodes: [
      { id: "battlecraft_redhand_practice", branch: "battlecraft", maxRank: 2 },
      { id: "battlecraft_deep_gash_practice", branch: "battlecraft", maxRank: 3 },
      { id: "battlecraft_brute_swing_practice", branch: "battlecraft", maxRank: 2, requires: ["battlecraft_redhand_practice"], requiresPointsInBranch: 2 },
      { id: "battlecraft_seasoned_form", branch: "battlecraft", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { attackPower: { add: 12 } } },
      { id: "battlecraft_forked_path", branch: "battlecraft", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "battlecraft_early_grave_practice", branch: "battlecraft", maxRank: 2, requires: ["battlecraft_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "bloodrush",
    classId: "warrior",
    name: "Bloodrush",
    icon: "axe",
    nodes: [
      { id: "bloodrush_measured_practice", branch: "bloodrush", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "bloodrush_steady_nerve", branch: "bloodrush", maxRank: 2, modifiersPerRank: { attackPower: { add: 10 } } },
      { id: "bloodrush_reaping_arc_practice", branch: "bloodrush", maxRank: 1, requires: ["bloodrush_measured_practice"], requiresPointsInBranch: 2 },
      { id: "bloodrush_reaping_arc_finesse", branch: "bloodrush", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "bloodrush_forked_path", branch: "bloodrush", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "bloodrush_reaver_strike_practice", branch: "bloodrush", maxRank: 2, requires: ["bloodrush_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "ironguard",
    classId: "warrior",
    name: "Ironguard",
    icon: "shield",
    nodes: [
      { id: "ironguard_measured_practice", branch: "ironguard", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
      { id: "vigil_steady_nerve", branch: "ironguard", maxRank: 3 },
      { id: "ironguard_quaking_blow_practice", branch: "ironguard", maxRank: 2, requires: ["ironguard_measured_practice"], requiresPointsInBranch: 2 },
      { id: "ironguard_armor_shear_practice", branch: "ironguard", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "vigil_forked_path", branch: "ironguard", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "ironguard_goad_practice", branch: "ironguard", maxRank: 2, requires: ["vigil_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "sacrament",
    classId: "paladin",
    name: "Sacrament",
    icon: "heart",
    nodes: [
      { id: "sacrament_mending_light_practice", branch: "sacrament", maxRank: 3 },
      { id: "sacrament_steady_nerve", branch: "sacrament", maxRank: 3, modifiersPerRank: { int: { add: 3 } } },
      { id: "sacrament_lightmend_practice", branch: "sacrament", maxRank: 2, requires: ["sacrament_mending_light_practice"], requiresPointsInBranch: 2 },
      { id: "sacrament_last_rite_practice", branch: "sacrament", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "sacrament_forked_path", branch: "sacrament", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "sacrament_veteran_instinct", branch: "sacrament", maxRank: 2, requires: ["sacrament_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
    ],
  },
  {
    id: "vigil",
    classId: "paladin",
    name: "Vigil",
    icon: "shield",
    nodes: [
      { id: "vigil_measured_practice", branch: "vigil", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
      { id: "vigil_steady_nerve", branch: "vigil", maxRank: 3 },
      { id: "vigil_decisive_motion", branch: "vigil", maxRank: 2, requires: ["vigil_measured_practice"], requiresPointsInBranch: 2 },
      { id: "vigil_ward_of_faith_practice", branch: "vigil", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "vigil_forked_path", branch: "vigil", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "vigil_steadfast_aura_practice", branch: "vigil", maxRank: 2, requires: ["vigil_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "requital",
    classId: "paladin",
    name: "Requital",
    icon: "hammer",
    nodes: [
      { id: "requital_oathbrand_practice", branch: "requital", maxRank: 3 },
      { id: "requital_steady_nerve", branch: "requital", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "requital_rite_of_expulsion_practice", branch: "requital", maxRank: 2, requires: ["requital_oathbrand_practice"], requiresPointsInBranch: 2 },
      { id: "requital_oathbrand_finesse", branch: "requital", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "requital_forked_path", branch: "requital", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "requital_sundering_gavel_practice", branch: "requital", maxRank: 2, requires: ["requital_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "packlord",
    classId: "hunter",
    name: "Packlord",
    icon: "feather",
    nodes: [
      { id: "packlord_measured_practice", branch: "packlord", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 }, sta: { add: 1 } } },
      { id: "packlord_steady_nerve", branch: "packlord", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
      { id: "packlord_harrier_s_guise_practice", branch: "packlord", maxRank: 2, requires: ["packlord_measured_practice"], requiresPointsInBranch: 2 },
      { id: "packlord_seasoned_form", branch: "packlord", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 1.5 } } },
      { id: "packlord_forked_path", branch: "packlord", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "packlord_veteran_instinct", branch: "packlord", maxRank: 2, requires: ["packlord_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
    ],
  },
  {
    id: "coldsight",
    classId: "hunter",
    name: "Coldsight",
    icon: "bow",
    nodes: [
      { id: "coldsight_fell_shot_practice", branch: "coldsight", maxRank: 3 },
      { id: "coldsight_steady_nerve", branch: "coldsight", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "coldsight_long_draw_practice", branch: "coldsight", maxRank: 2, requires: ["coldsight_fell_shot_practice"], requiresPointsInBranch: 2 },
      { id: "coldsight_volley_practice", branch: "coldsight", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "coldsight_forked_path", branch: "coldsight", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "coldsight_long_draw_finesse", branch: "coldsight", maxRank: 2, requires: ["coldsight_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "fieldcraft",
    classId: "hunter",
    name: "Fieldcraft",
    icon: "crossbow",
    nodes: [
      { id: "fieldcraft_measured_practice", branch: "fieldcraft", maxRank: 3, modifiersPerRank: { agi: { add: 1 } } },
      { id: "fieldcraft_steady_nerve", branch: "fieldcraft", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "fieldcraft_fettering_slash_practice", branch: "fieldcraft", maxRank: 2, requires: ["fieldcraft_measured_practice"], requiresPointsInBranch: 2 },
      { id: "fieldcraft_fevered_draw_practice", branch: "fieldcraft", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "fieldcraft_forked_path", branch: "fieldcraft", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "fieldcraft_veteran_instinct", branch: "fieldcraft", maxRank: 2, requires: ["fieldcraft_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { agi: { add: 5 } } },
    ],
  },
  {
    id: "knifework",
    classId: "rogue",
    name: "Knifework",
    icon: "poison",
    nodes: [
      { id: "knifework_dirt_nap_practice", branch: "knifework", maxRank: 3 },
      { id: "knifework_steady_nerve", branch: "knifework", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "knifework_decisive_motion", branch: "knifework", maxRank: 2, requires: ["knifework_dirt_nap_practice"], requiresPointsInBranch: 2 },
      { id: "knifework_throat_wire_practice", branch: "knifework", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "knifework_forked_path", branch: "knifework", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "knifework_wicked_slash_practice", branch: "knifework", maxRank: 2, requires: ["knifework_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "thuggery",
    classId: "rogue",
    name: "Thuggery",
    icon: "dagger",
    nodes: [
      { id: "thuggery_eye_jab_practice", branch: "thuggery", maxRank: 3 },
      { id: "thuggery_steady_nerve", branch: "thuggery", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
      { id: "thuggery_swift_heels_practice", branch: "thuggery", maxRank: 2, requires: ["thuggery_eye_jab_practice"], requiresPointsInBranch: 2 },
      { id: "thuggery_seasoned_form", branch: "thuggery", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "thuggery_forked_path", branch: "thuggery", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "thuggery_veteran_instinct", branch: "thuggery", maxRank: 2, requires: ["thuggery_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { attackPower: { multiply: 1.08 } } },
    ],
  },
  {
    id: "skulduggery",
    classId: "rogue",
    name: "Skulduggery",
    icon: "cloak",
    nodes: [
      { id: "skulduggery_measured_practice", branch: "skulduggery", maxRank: 3, modifiersPerRank: { agi: { add: 1 } } },
      { id: "skulduggery_craven_thrust_practice", branch: "skulduggery", maxRank: 3 },
      { id: "skulduggery_smokestep_practice", branch: "skulduggery", maxRank: 2, requires: ["skulduggery_measured_practice"], requiresPointsInBranch: 2 },
      { id: "skulduggery_lurker_s_strike_practice", branch: "skulduggery", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "skulduggery_forked_path", branch: "skulduggery", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "skulduggery_veteran_instinct", branch: "skulduggery", maxRank: 2, requires: ["skulduggery_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { agi: { add: 4 }, critPct: { add: 1 } } },
    ],
  },
  {
    id: "doctrine",
    classId: "priest",
    name: "Doctrine",
    icon: "shield",
    nodes: [
      { id: "doctrine_measured_practice", branch: "doctrine", maxRank: 3, modifiersPerRank: { sta: { add: 2 }, spi: { add: 1 } } },
      { id: "doctrine_steady_nerve", branch: "doctrine", maxRank: 3 },
      { id: "doctrine_psalm_of_warding_practice", branch: "doctrine", maxRank: 2, requires: ["doctrine_measured_practice"], requiresPointsInBranch: 2 },
      { id: "doctrine_psalm_of_warding_finesse", branch: "doctrine", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "doctrine_forked_path", branch: "doctrine", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "doctrine_smite_practice", branch: "doctrine", maxRank: 2, requires: ["doctrine_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "benison",
    classId: "priest",
    name: "Benison",
    icon: "heart",
    nodes: [
      { id: "benison_measured_practice", branch: "benison", maxRank: 3 },
      { id: "benison_lingering_grace_practice", branch: "benison", maxRank: 3 },
      { id: "benison_smite_practice", branch: "benison", maxRank: 2, requires: ["benison_measured_practice"], requiresPointsInBranch: 2 },
      { id: "benison_seasoned_form", branch: "benison", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { armor: { multiply: 1.05 } } },
      { id: "benison_forked_path", branch: "benison", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "benison_veteran_instinct", branch: "benison", maxRank: 2, requires: ["benison_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
    ],
  },
  {
    id: "vespers",
    classId: "priest",
    name: "Vespers",
    icon: "skull",
    nodes: [
      { id: "vespers_mindfracture_practice", branch: "vespers", maxRank: 3 },
      { id: "vespers_dirge_of_decay_practice", branch: "vespers", maxRank: 3 },
      { id: "vespers_litany_of_woe_practice", branch: "vespers", maxRank: 2, requires: ["vespers_mindfracture_practice"], requiresPointsInBranch: 2 },
      { id: "vespers_mindfracture_finesse", branch: "vespers", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "vespers_forked_path", branch: "vespers", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "vespers_veteran_instinct", branch: "vespers", maxRank: 2, requires: ["vespers_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { armor: { multiply: 1.05 } } },
    ],
  },
  {
    id: "thundercall",
    classId: "shaman",
    name: "Thundercall",
    icon: "lightning",
    nodes: [
      { id: "thundercall_arc_bolt_practice", branch: "thundercall", maxRank: 3 },
      { id: "thundercall_cinder_jolt_practice", branch: "thundercall", maxRank: 3 },
      { id: "thundercall_earthen_jolt_practice", branch: "thundercall", maxRank: 2, requires: ["thundercall_arc_bolt_practice"], requiresPointsInBranch: 2 },
      { id: "thundercall_seasoned_form", branch: "thundercall", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "thundercall_forked_path", branch: "thundercall", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "thundercall_arc_bolt_finesse", branch: "thundercall", maxRank: 2, requires: ["thundercall_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "warspirit",
    classId: "shaman",
    name: "Warspirit",
    icon: "fist",
    nodes: [
      { id: "warspirit_measured_practice", branch: "warspirit", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
      { id: "warspirit_steady_nerve", branch: "warspirit", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 } } },
      { id: "warspirit_stonebound_weapon_practice", branch: "warspirit", maxRank: 2, requires: ["warspirit_measured_practice"], requiresPointsInBranch: 2 },
      { id: "warspirit_seasoned_form", branch: "warspirit", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
      { id: "warspirit_forked_path", branch: "warspirit", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "warspirit_veteran_instinct", branch: "warspirit", maxRank: 2, requires: ["warspirit_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "spiritmend",
    classId: "shaman",
    name: "Spiritmend",
    icon: "potionBlue",
    nodes: [
      { id: "spiritmend_mending_waters_practice", branch: "spiritmend", maxRank: 3 },
      { id: "spiritmend_mending_waters_finesse", branch: "spiritmend", maxRank: 3 },
      { id: "spiritmend_decisive_motion", branch: "spiritmend", maxRank: 2, requires: ["spiritmend_mending_waters_practice"], requiresPointsInBranch: 2, modifiersPerRank: { armor: { multiply: 1.05 } } },
      { id: "spiritmend_seasoned_form", branch: "spiritmend", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { spi: { add: 2 } } },
      { id: "spiritmend_forked_path", branch: "spiritmend", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "spiritmend_veteran_instinct", branch: "spiritmend", maxRank: 2, requires: ["spiritmend_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { int: { add: 2 } } },
    ],
  },
  {
    id: "aethermancy",
    classId: "mage",
    name: "Aethermancy",
    icon: "star",
    nodes: [
      { id: "aethermancy_aether_darts_practice", branch: "aethermancy", maxRank: 3 },
      { id: "aethermancy_steady_nerve", branch: "aethermancy", maxRank: 3 },
      { id: "aethermancy_bewitch_practice", branch: "aethermancy", maxRank: 2, requires: ["aethermancy_aether_darts_practice"], requiresPointsInBranch: 2 },
      { id: "aethermancy_seasoned_form", branch: "aethermancy", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { int: { add: 2 } } },
      { id: "aethermancy_forked_path", branch: "aethermancy", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "aethermancy_aetherburst_practice", branch: "aethermancy", maxRank: 2, requires: ["aethermancy_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "pyromancy",
    classId: "mage",
    name: "Pyromancy",
    icon: "fire",
    nodes: [
      { id: "pyromancy_cinderbolt_practice", branch: "pyromancy", maxRank: 3 },
      { id: "pyromancy_steady_nerve", branch: "pyromancy", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
      { id: "pyromancy_cinderfall_practice", branch: "pyromancy", maxRank: 2, requires: ["pyromancy_cinderbolt_practice"], requiresPointsInBranch: 2 },
      { id: "pyromancy_scald_practice", branch: "pyromancy", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "pyromancy_forked_path", branch: "pyromancy", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "pyromancy_pyrelance_practice", branch: "pyromancy", maxRank: 2, requires: ["pyromancy_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "cryomancy",
    classId: "mage",
    name: "Cryomancy",
    icon: "frost",
    nodes: [
      { id: "cryomancy_rimelance_practice", branch: "cryomancy", maxRank: 3 },
      { id: "cryomancy_steady_nerve", branch: "cryomancy", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 } } },
      { id: "cryomancy_icebind_practice", branch: "cryomancy", maxRank: 2, requires: ["cryomancy_rimelance_practice"], requiresPointsInBranch: 2 },
      { id: "cryomancy_seasoned_form", branch: "cryomancy", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
      { id: "cryomancy_forked_path", branch: "cryomancy", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "cryomancy_veteran_instinct", branch: "cryomancy", maxRank: 2, requires: ["cryomancy_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
    ],
  },
  {
    id: "hexcraft",
    classId: "warlock",
    name: "Hexcraft",
    icon: "poison",
    nodes: [
      { id: "hexcraft_hex_of_anguish_practice", branch: "hexcraft", maxRank: 3 },
      { id: "hexcraft_blackrot_practice", branch: "hexcraft", maxRank: 3 },
      { id: "hexcraft_consume_practice", branch: "hexcraft", maxRank: 2, requires: ["hexcraft_hex_of_anguish_practice"], requiresPointsInBranch: 2 },
      { id: "hexcraft_hex_of_anguish_finesse", branch: "hexcraft", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "hexcraft_forked_path", branch: "hexcraft", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "hexcraft_blackrot_finesse", branch: "hexcraft", maxRank: 2, requires: ["hexcraft_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "pactbound",
    classId: "warlock",
    name: "Pactbound",
    icon: "wing",
    nodes: [
      { id: "pactbound_measured_practice", branch: "pactbound", maxRank: 3, modifiersPerRank: { sta: { add: 3 } } },
      { id: "pactbound_steady_nerve", branch: "pactbound", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.03 } } },
      { id: "pactbound_consume_practice", branch: "pactbound", maxRank: 2, requires: ["pactbound_measured_practice"], requiresPointsInBranch: 2 },
      { id: "pactbound_seasoned_form", branch: "pactbound", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { maxHp: { multiply: 1.04 } } },
      { id: "pactbound_forked_path", branch: "pactbound", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "pactbound_veteran_instinct", branch: "pactbound", maxRank: 2, requires: ["pactbound_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { sta: { multiply: 1.06 }, armor: { multiply: 1.06 } } },
    ],
  },
  {
    id: "ruination",
    classId: "warlock",
    name: "Ruination",
    icon: "bomb",
    nodes: [
      { id: "ruination_gloom_bolt_practice", branch: "ruination", maxRank: 3 },
      { id: "ruination_burning_pact_practice", branch: "ruination", maxRank: 3 },
      { id: "ruination_decisive_motion", branch: "ruination", maxRank: 2, requires: ["ruination_gloom_bolt_practice"], requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
      { id: "ruination_sear_practice", branch: "ruination", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "ruination_forked_path", branch: "ruination", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "ruination_gloom_bolt_finesse", branch: "ruination", maxRank: 2, requires: ["ruination_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "moongrove",
    classId: "druid",
    name: "Moongrove",
    icon: "star",
    nodes: [
      { id: "moongrove_wildbolt_practice", branch: "moongrove", maxRank: 3 },
      { id: "moongrove_lunar_tempest_practice", branch: "moongrove", maxRank: 3 },
      { id: "moongrove_decisive_motion", branch: "moongrove", maxRank: 2, requires: ["moongrove_wildbolt_practice"], requiresPointsInBranch: 2 },
      { id: "moongrove_seasoned_form", branch: "moongrove", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
      { id: "moongrove_forked_path", branch: "moongrove", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "moongrove_wildbolt_finesse", branch: "moongrove", maxRank: 2, requires: ["moongrove_forked_path"], requiresPointsInBranch: 8 },
    ],
  },
  {
    id: "wildfang",
    classId: "druid",
    name: "Wildfang",
    icon: "fist",
    nodes: [
      { id: "wildfang_measured_practice", branch: "wildfang", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
      { id: "wildfang_steady_nerve", branch: "wildfang", maxRank: 3 },
      { id: "wildfang_wildbolt_practice", branch: "wildfang", maxRank: 2, requires: ["wildfang_measured_practice"], requiresPointsInBranch: 2 },
      { id: "wildfang_seasoned_form", branch: "wildfang", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { agi: { add: 2 } } },
      { id: "wildfang_forked_path", branch: "wildfang", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "wildfang_veteran_instinct", branch: "wildfang", maxRank: 2, requires: ["wildfang_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { sta: { multiply: 1.05 }, attackPower: { multiply: 1.05 } } },
    ],
  },
  {
    id: "groveheart",
    classId: "druid",
    name: "Groveheart",
    icon: "leaf",
    nodes: [
      { id: "groveheart_wildbloom_practice", branch: "groveheart", maxRank: 3 },
      { id: "groveheart_steady_nerve", branch: "groveheart", maxRank: 3 },
      { id: "groveheart_wildmend_practice", branch: "groveheart", maxRank: 2, requires: ["groveheart_wildbloom_practice"], requiresPointsInBranch: 2 },
      { id: "groveheart_wildmend_finesse", branch: "groveheart", maxRank: 2, requiresPointsInBranch: 2 },
      { id: "groveheart_forked_path", branch: "groveheart", maxRank: 1, requiresPointsInBranch: 5 },
      { id: "groveheart_veteran_instinct", branch: "groveheart", maxRank: 2, requires: ["groveheart_forked_path"], requiresPointsInBranch: 8, modifiersPerRank: { spi: { add: 3 } } },
    ],
  },
];

export function specsForClass(classId: string): SpecDef[] {
  return SPECS.filter((spec) => spec.classId === classId);
}

export const TALENT_POINTS_RULE: { firstLevel: number; perLevel: number } = {
  firstLevel: 10,
  perLevel: 1,
};
