import type { ClassDef } from "../../model";

export const PALADIN_CLASS: readonly ClassDef[] = [
  {
    id: "paladin",
    name: "Oathkeeper",
    icon: "hammer",
    color: "#F58CBA",
    resource: "mana",
    baseHp: 55,
    hpPerLevel: 17,
    baseResource: 80,
    resourcePerLevel: 20,
    baseStats: { str: 22, agi: 17, sta: 22, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 1, spi: 1, armor: 12 },
    startWeapon: "training_mace",
    abilities: [
      {
        id: "oathbrand",
        name: "Oathbrand",
        icon: "star",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 4,
        perLevel: 0.4,
        duration: 30,
        selfTarget: true,
      },
      {
        id: "mending_light",
        name: "Mending Light",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 1,
        cost: 35,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 46.5,
        perLevel: 8.9,
        selfTarget: true,
      },
      {
        id: "steadfast_aura",
        name: "Steadfast Aura",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 10,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "oath_of_iron",
        name: "Oath of Iron",
        icon: "buffArrow",
        school: "holy",
        kind: "buff",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 10,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "ward_of_faith",
        name: "Ward of Faith",
        icon: "amulet",
        school: "holy",
        kind: "buff",
        levelReq: 6,
        cost: 15,
        castTime: 0,
        cooldown: 180,
        range: 0,
        base: 50,
        perLevel: 3.3,
        duration: 10,
        selfTarget: true,
      },
      {
        id: "last_rite",
        name: "Last Rite",
        icon: "wing",
        school: "holy",
        kind: "heal",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 600,
        range: 30,
        base: 250,
        perLevel: 19.4,
        selfTarget: true,
      },
      {
        id: "lightmend",
        name: "Lightmend",
        icon: "feather",
        school: "holy",
        kind: "heal",
        levelReq: 12,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 69,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "rite_of_expulsion",
        name: "Rite of Expulsion",
        icon: "cross",
        school: "holy",
        kind: "damage",
        levelReq: 14,
        cost: 55,
        castTime: 0,
        cooldown: 15,
        range: 30,
        base: 51,
        perLevel: 0,
      },
      {
        id: "holy_ground",
        name: "Holy Ground",
        icon: "fire",
        school: "holy",
        kind: "aoe",
        levelReq: 18,
        cost: 60,
        castTime: 0,
        cooldown: 8,
        range: 0,
        base: 31,
        perLevel: 0,
        aoeRadius: 8,
        duration: 10,
        tickInterval: 2,
      },
      {
        id: "burning_oath",
        name: "Burning Oath",
        icon: "torch",
        school: "holy",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 160,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "requital_aura",
        name: "Requital Aura",
        icon: "ring",
        school: "holy",
        kind: "buff",
        levelReq: 16,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "sundering_gavel",
        name: "Sundering Gavel",
        icon: "hourglass",
        school: "holy",
        kind: "buff",
        levelReq: 8,
        cost: 30,
        castTime: 0,
        cooldown: 60,
        range: 10,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 3 },
      },
    ],
  },
];
