// Generated by scripts/author-models.mjs. Original geometry; do not hand-edit.
import keep_player from "./art/keep_player.glb?url";
import keep_enemy from "./art/keep_enemy.glb?url";
import barracks from "./art/barracks.glb?url";
import farm from "./art/farm.glb?url";
import guard_tower from "./art/guard_tower.glb?url";
import peasant from "./art/peasant.glb?url";
import footman from "./art/footman.glb?url";
import rifleman from "./art/rifleman.glb?url";
import hero from "./art/hero.glb?url";
import grunt from "./art/grunt.glb?url";
import reaver from "./art/reaver.glb?url";
import banner_blue from "./art/banner_blue.glb?url";
import banner_red from "./art/banner_red.glb?url";
import torch from "./art/torch.glb?url";
import barrel from "./art/barrel.glb?url";
import goldmine from "./art/goldmine.glb?url";
import woods from "./art/woods.glb?url";
export const authoredModels = {
  keep_player,
  keep_enemy,
  barracks,
  farm,
  guard_tower,
  peasant,
  footman,
  rifleman,
  hero,
  grunt,
  reaver,
  banner_blue,
  banner_red,
  torch,
  barrel,
  goldmine,
  woods,
};
