import type { ActionCodesMap } from "@jgengine/core/input/actionBindings";

export const keybinds: ActionCodesMap = {
  moveForward: ["KeyW", "padaxis:1-", "pad:7"],
  moveBack: ["KeyS", "padaxis:1+", "pad:6"],
  moveLeft: ["KeyA", "padaxis:0-"],
  moveRight: ["KeyD", "padaxis:0+"],
  jump: ["Space", "pad:0"],
  sprint: ["ShiftLeft", "pad:10"],
  flightThrottleUp: ["ArrowUp", "pad:12"],
  flightThrottleDown: ["ArrowDown", "pad:13"],
  flightYawLeft: ["KeyZ", "padaxis:2-"],
  flightYawRight: ["KeyC", "padaxis:2+"],
  flightAirbrake: ["KeyX", "pad:4"],
  flightVectorToggle: ["KeyV", "pad:11"],
  interact: ["KeyE", "pad:2"],
  fire: { hold: ["mouse0", "pad:5"], repeatMs: 60 },
  throwGrenade: ["KeyG", "pad:3"],
  useMedkit: ["KeyQ", "pad:8"],
  exitVehicle: ["KeyF", "pad:1"],
  selectSlot1: ["Digit1", "pad:14"],
  selectSlot2: ["Digit2", "pad:15"],
  selectSlot3: ["Digit3"],
  selectSlot4: ["Digit4"],
};
